### ISSUE TITLE
Problems with "/firmware/image/" path

### ISSUE THREAD

**Issue by yshalsager** [ardadem/xiaomi-flashable-firmware-creator#1]
Details:
https://forum.xda-developers.com/showpost.php?p=75378337&postcount=20

**Comment by ardadem** [comment]
https://github.com/xiaomi-firmware-updater/xiaomi-flashable-firmware-creator/commit/6e376a6303dc19423539fe1e98d998ac31cf2d08

seems solved

**Comment by yshalsager** [comment]
@ardadem yes, it's solved

**Comment by ardadem** [comment]
also https://github.com/ardadem/xiaomi-flashable-firmware-creator/commit/87190eaacea9e355194d8ad67ee590c686a2c664
